name: Frist Workflow

on: 
 push:
  branches:
    - main

jobs:
     example-jobs:      
      runs-on: ubuntu-latest

      steps:
       - name: print a welcome massage
         run: echo"welcome to our fisrt gihupaction workflow"
       
        


        
  
